<a href="https://colab.research.google.com/github/perlatomdpi/PyTorch/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Basics
A tensor is a mathematical object that describes the relationship between other mathematical objects that are all linked together. <br>
They are commonly shown as an array of numbers: <br>
A vector is 1D tensor, and a matix is a 2D tensor. <br>
More info about tensor cores at:<br>
https://www.techspot.com/article/2049-what-are-tensor-cores/


# Convert numpy array to a pytorch tensor

In [ ]:
import torch
import numpy as np
torch.__version__

In [ ]:
# Create numpy array
arr = np.array([1, 2, 3, 4, 5])
# Check data type
arr.dtype
type(arr)

In [ ]:
# Convert array to a tensor method 1 specific foor numpy array
x = torch.from_numpy(arr)
type(x)

In [ ]:
# Convert array to a tensor method 2 generalized method
torch.as_tensor(arr)

In [10]:
# 2D numpy array
arr2d = np.arange(0.0, 12.0)
arr2d = arr2d.reshape(4, 3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [11]:
# Convert 2D array to a tensor
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

# Create tensor from scratch

In [12]:
# Create numpy array
new_arr = np.array([1, 2, 3])

# Create float tensor
torch.Tensor(new_arr)

tensor([1., 2., 3.])

In [14]:
# Arrange Tensor
torch.arange(0, 18, 2).reshape(3, 3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [18]:
# Arrange Tensor linearly
torch.linspace(0, 18, 12).reshape(3, 4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [19]:
# Convert data type of a tensor
my_tensor = torch.tensor([1, 2, 3])
my_tensor.dtype

torch.int64

In [20]:
my_tensor = my_tensor.type(torch.int32)
my_tensor.dtype

torch.int32

In [22]:
# Create a random tensor normal distributed
# With mean=0 and sd=1
torch.randn(5, 10) 

tensor([[-0.0381,  0.7299, -0.3097, -1.6117,  0.9652, -0.7952,  1.1607,  1.4216,
          0.3530, -0.4795],
        [ 0.3316, -1.2872,  0.1351,  0.1309,  0.1298,  0.5105, -0.7345, -1.0937,
          1.4300,  0.6995],
        [-0.1262,  0.7891,  0.8821,  0.2101, -2.6839, -1.0328, -0.8145,  0.6564,
          0.1226,  1.9781],
        [-0.1881, -0.5877,  0.9106,  0.9686,  0.0836, -0.5705, -0.5397,  1.1815,
          0.0206, -0.9617],
        [-1.1503, -1.7290,  0.5379,  0.4237, -0.4581, -0.8938,  1.9590,  0.2946,
         -1.4603, -2.2947]])

# Tensor operations

In [24]:
# Get single value
x  = torch.arange(6).reshape(3, 2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [25]:
x[1,1]

tensor(3)

In [26]:
# Get singluar column
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [30]:
# Sum tensors element by element
a  = torch.tensor([1.,2., 3.])
b = torch.tensor([4., 4., 6.])
a + b
torch.add(a,b)

tensor([5., 6., 9.])

In [31]:
# Multiplication tensors element by element
a.mul(b)

tensor([ 4.,  8., 18.])

In [36]:
# Matrix multiplication
a  = torch.tensor([[0, 2, 4], [1, 3, 5]])
b  = torch.tensor([[0, 7], [8, 9], [10, 11]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [35]:
b

tensor([[ 0,  7],
        [ 8,  9],
        [10, 11]])

In [37]:
torch.mm(a, b)

tensor([[56, 62],
        [74, 89]])

In [40]:
# L2 or Euclidian Normalization
# It is the magnitude of the vector
x  = torch.tensor([1., 2., 3., 4., 5.])
x.norm()

tensor(7.4162)

In [42]:
# Give number of elements in a tensor
x.numel()
len(x)

5

In [43]:
# Give number of elements in a multidimentional tensor
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [44]:
a.numel()

6