<a href="https://colab.research.google.com/github/perlatomdpi/PyTorch/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Basics
A tensor is a mathematical object that describes the relationship between other mathematical objects that are all linked together. <br>
They are commonly shown as an array of numbers: <br>
A vector is 1D tensor, and a matix is a 2D tensor. <br>
More info about tensor cores at:<br>
https://www.techspot.com/article/2049-what-are-tensor-cores/


# Convert numpy array to a pytorch tensor

In [ ]:
import torch
import numpy as np
torch.__version__

In [ ]:
# Create numpy array
arr = np.array([1, 2, 3, 4, 5])
# Check data type
arr.dtype
type(arr)

In [ ]:
# Convert array to a tensor method 1 specific foor numpy array
x = torch.from_numpy(arr)
type(x)

In [ ]:
# Convert array to a tensor method 2 generalized method
torch.as_tensor(arr)

In [10]:
# 2D numpy array
arr2d = np.arange(0.0, 12.0)
arr2d = arr2d.reshape(4, 3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [11]:
# Convert 2D array to a tensor
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

# Create tensor from scratch

In [12]:
# Create numpy array
new_arr = np.array([1, 2, 3])

# Create float tensor
torch.Tensor(new_arr)

tensor([1., 2., 3.])

In [14]:
# Arrange Tensor
torch.arange(0, 18, 2).reshape(3, 3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [18]:
# Arrange Tensor linearly
torch.linspace(0, 18, 12).reshape(3, 4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])